Repository FLEX-RATE/flexrate-back, pull requests merged in 2025-04, with the labels that each got.

#2 feat : 엔티티 구현
  Dockerfile
  docker-compose.yml
  src/main/java/com/flexrate/flexrate_back/auth/domain/Authentication.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/FidoCredential.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/MfaLog.java
  src/main/java/com/flexrate/flexrate_back/auth/enums/AuthMethod.java
  src/main/java/com/flexrate/flexrate_back/auth/enums/AuthResult.java
  src/main/java/com/flexrate/flexrate_back/auth/enums/MfaType.java
  src/main/java/com/flexrate/flexrate_back/finantialdata/domain/UserFinancialData.java
  src/main/java/com/flexrate/flexrate_back/finantialdata/enums/UserFinancialDataType.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/Interest.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanProduct.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanTransaction.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/LoanApplicationStatus.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/TransactionStatus.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/TransactionType.java
  src/main/java/com/flexrate/flexrate_back/log/domain/AuditLog.java
  src/main/java/com/flexrate/flexrate_back/log/enums/EventType.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/enums/LoginMethod.java
  src/main/java/com/flexrate/flexrate_back/member/enums/UserStatus.java
  src/main/java/com/flexrate/flexrate_back/notification/domain/Notification.java
  src/main/java/com/flexrate/flexrate_back/notification/enums/NotificationType.java
  src/main/resources/application.yml
  src/main/resources/properties/env_example.properties
Labels: feat

#4 update: env 의존성 주입 최적화 및 Dockerfile 개선
  .env.example
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/flexrate/flexrate_back/config/PropertyConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: chore

#8 chore: Exception 처리 표준화 작업
  src/main/java/com/flexrate/flexrate_back/common/TestController.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/exception/FlexrateException.java
  src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java
  src/main/java/com/flexrate/flexrate_back/common/util/ProfileUtil.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: chore

#11 feat: 관리자용 사용자 목록 검색 API 구현
  src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java
  src/main/java/com/flexrate/flexrate_back/common/config/QuerydslConfig.java
  src/main/java/com/flexrate/flexrate_back/common/dto/PaginationInfo.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/exception/FlexrateException.java
  src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java
  src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
  src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthChecker.java
  src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthCheckerImpl.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchRequest.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchResponse.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberSummaryDto.java
  src/main/java/com/flexrate/flexrate_back/member/enums/MemberStatus.java
  src/main/java/com/flexrate/flexrate_back/member/enums/Sex.java
  src/main/java/com/flexrate/flexrate_back/member/mapper/MemberMapper.java
Labels: feat

#16 chore: ErrorCode HttpStatus 추가
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java
Labels: chore

#17 feature: 대출 신청 사전 정보 입력 API 구현
  src/main/java/com/flexrate/flexrate_back/common/config/RestTemplateConfig.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanPreApplicationController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanPreApplicationService.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/EducationStatus.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/EmploymentType.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/LoanPurpose.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/ResidenceType.java
  src/test/java/com/flexrate/flexrate_back/loan/api/LoanPreApplicationControllerTest.java
  src/test/java/com/flexrate/flexrate_back/loan/application/LoanPreApplicationServiceTest.java
  src/test/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationRequestTest.java
Labels: feat, chore

#18 feature: 관리자용 특정 사용자 정보 수정 API 구현
  src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PatchMemberRequest.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PatchMemberResponse.java
  src/test/java/com/flexrate/flexrate_back/member/application/MemberAdminServiceTest.java
Labels: feat

#21 feat: 사용자 입금 내역 상세 조회 API 구현
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/UserFinancialData.java
  src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialDataType.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/TransactionHistoryResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/TransactionHistorySummaryDto.java
  src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanTransactionMapper.java
  src/test/java/com/flexrate/flexrate_back/loan/api/LoanAdminControllerTest.java
Labels: feat
