Repository FLEX-RATE/flexrate-back, pull requests merged in 2025-05, with the labels that each got.

#25 fix: 대출 심사 신청(구: 대출 신청 사전 정보 입력) API 관련 엔티티 및 관련 파일명 클래스명 수정
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanReviewApplicationController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanReviewApplicationService.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationResponse.java
  src/main/java/com/flexrate/flexrate_back/member/enums/ConsumeGoal.java
  src/main/java/com/flexrate/flexrate_back/member/enums/ConsumptionType.java
  src/test/java/com/flexrate/flexrate_back/loan/api/LoanReviewApplicationControllerTest.java
  src/test/java/com/flexrate/flexrate_back/loan/application/LoanReviewApplicationServiceTest.java
  src/test/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationRequestTest.java
Labels: fix

#30 chore: JWT 인증/인가 구현 및 Swagger, Spring Security 설정
  build.gradle
  src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java
  src/main/java/com/flexrate/flexrate_back/auth/api/TestTokenApiController.java
  src/main/java/com/flexrate/flexrate_back/auth/api/TokenApiController.java
  src/main/java/com/flexrate/flexrate_back/auth/application/RefreshTokenService.java
  src/main/java/com/flexrate/flexrate_back/auth/application/TokenService.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtProperties.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtTokenProvider.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/RefreshToken.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/TokenAuthenticationFilter.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/flexrate/flexrate_back/auth/dto/CreateAccessTokenRequest.java
  src/main/java/com/flexrate/flexrate_back/auth/dto/CreateAccessTokenResponse.java
  src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java
  src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfigProperties.java
  src/main/java/com/flexrate/flexrate_back/common/config/SwaggerConfig.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorResponse.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java
  src/main/java/com/flexrate/flexrate_back/member/enums/Role.java
  src/main/java/com/flexrate/flexrate_back/member/security/MemberDetails.java
  src/main/resources/application.yml
  src/test/java/com/flexrate/flexrate_back/jwt/JwtFactory.java
  src/test/java/com/flexrate/flexrate_back/jwt/TokenApiControllerTest.java
  src/test/java/com/flexrate/flexrate_back/jwt/TokenProviderTest.java
Labels: chore

#29 feat: 대출 상태 변경 API 구현
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanApplicationRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationStatusUpdateRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationStatusUpdateResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/LoanApplicationStatus.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
  src/test/java/com/flexrate/flexrate_back/loan/application/LoanAdminServiceTest.java
Labels: feat

#32 feat: 회원가입 등록 API 구현
  src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java
  src/main/java/com/flexrate/flexrate_back/member/api/SignUpController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupResponseDTO.java
  src/main/java/com/flexrate/flexrate_back/member/enums/Role.java
  src/test/java/com/flexrate/flexrate_back/member/application/MemberServiceTest.java
Labels: feat

#35 Feat : 대출 상품 로직 구현 및 대출 관련 엔티티 수정
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanProductController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanProductService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanReviewApplicationService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanProductRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/Interest.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanProduct.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanProductSummaryDto.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/LoanApplicationStatus.java
  src/test/java/com/flexrate/flexrate_back/loan/api/LoanAdminControllerTest.java
  src/test/java/com/flexrate/flexrate_back/loan/api/LoanReviewApplicationControllerTest.java
  src/test/java/com/flexrate/flexrate_back/loan/application/LoanAdminServiceTest.java
  src/test/java/com/flexrate/flexrate_back/loan/application/LoanReviewApplicationServiceTest.java
  src/test/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationRequestTest.java
Labels: feat

#42 feature: 관리자용 사용자 정보 상세 조회 API 구현
  src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberDetailResponse.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PatchMemberResponse.java
  src/test/java/com/flexrate/flexrate_back/member/application/MemberAdminServiceTest.java
Labels: feat

#40 Feat: 대출 심사 로직 수정
  src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java
  src/main/java/com/flexrate/flexrate_back/common/config/JpaAuditingConfig.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanController.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanReviewApplicationController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanApplicationRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/Interest.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanProduct.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanApplicationMapper.java
  src/test/java/com/flexrate/flexrate_back/loan/LoanProductTest.java
  src/test/java/com/flexrate/flexrate_back/loan/LoanTest.java
Labels: feat

#26 chore: ELK 로그 수집 및 시각화 설정
  .env.example
  Dockerfile
  docker-compose.yml
  filebeat/filebeat.yml
  logstash/pipeline/logstash.conf
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
  workflow/dev_docker_rebuild.sh
  workflow/dev_run.sh
  workflow/prod_docker_back_deploy.sh
Labels: chore

#51 fix: [공통] 관리자 권한 검증 로직 추가
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
  src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthChecker.java
  src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthCheckerImpl.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
Labels: fix

#50 Feat : 대출 신청 및 조회 구현
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationResultResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanApplicationMapper.java
Labels: feat

#57 feature: 마이페이지 개인 정보 조회/수정 및 소비 타입별 목표 리스트 조회 API 구현
  src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/member/api/MemberController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/dto/ConsumeGoalResponse.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MypageResponse.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MypageUpdateRequest.java
  src/main/java/com/flexrate/flexrate_back/member/enums/ConsumeGoal.java
Labels: feat

#58 Feat: 대시보드 구현
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/loan/api/InterestController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/InterestService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/InterestRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/InterestAnalysisRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/InterestResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/InterestStatsDto.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/InterestSummaryResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/PeriodType.java
Labels: feat

#61 feature: 대출 현황 리스트 조회 API 구현
  src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanAdminQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanAdminQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchRequest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchSummaryDto.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/LoanType.java
  src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanApplicationMapper.java
  src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
Labels: feat

#60 feature: 소비습관 리포트 조회 API 작업
  src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java
  src/main/java/com/flexrate/flexrate_back/common/converter/YearMonthAttributeConverter.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/UserFinancialData.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataRepository.java
  src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialCategory.java
  src/main/java/com/flexrate/flexrate_back/report/api/ConsumptionHabitReportController.java
  src/main/java/com/flexrate/flexrate_back/report/api/ReportStatisticsController.java
  src/main/java/com/flexrate/flexrate_back/report/api/SchedulerTestController.java
  src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportService.java
  src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportServiceImpl.java
  src/main/java/com/flexrate/flexrate_back/report/application/ReportStatisticsService.java
  src/main/java/com/flexrate/flexrate_back/report/client/ConsumptionReportApiClient.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
  src/main/java/com/flexrate/flexrate_back/report/domain/repository/ConsumptionHabitReportRepository.java
  src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionCategoryRatioResponse.java
  src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionCategoryStatsResponse.java
  src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionHabitReportResponse.java
  src/main/java/com/flexrate/flexrate_back/report/scheduler/ConsumptionHabitReportScheduler.java
Labels: feat

#64 fix: 관리자용 사용자 정보 상세 조회 API 로직 수정
  src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberDetailResponse.java
Labels: fix

#68 fix: 고객 리스트 조회 API 개선
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchRequest.java
Labels: fix

#70 fIX: 고객 리스트 조회 쿼리 - 거래 횟수 범위 조건을 기반으로 올바른 결과를 반환하도록 쿼리 로직 개선
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
Labels: fix

#45 Feat: 로그인 API
  .gitignore
  build.gradle
  src/main/java/com/flexrate/flexrate_back/auth/api/EmailController.java
  src/main/java/com/flexrate/flexrate_back/auth/api/TokenApiController.java
  src/main/java/com/flexrate/flexrate_back/auth/application/EmailService.java
  src/main/java/com/flexrate/flexrate_back/auth/application/TokenService.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/Authentication.java
  src/main/java/com/flexrate/flexrate_back/auth/domain/FidoCredential.java
  src/main/java/com/flexrate/flexrate_back/auth/dto/EmailRequest.java
  src/main/java/com/flexrate/flexrate_back/auth/enums/MfaType.java
  src/main/java/com/flexrate/flexrate_back/common/config/EmailConfig.java
  src/main/java/com/flexrate/flexrate_back/common/dto/EmailVerificationRequest.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/common/util/EmailMessage.java
  src/main/java/com/flexrate/flexrate_back/common/util/EmailSender.java
  src/main/java/com/flexrate/flexrate_back/common/util/RandomStringUtil.java
  src/main/java/com/flexrate/flexrate_back/common/util/StringRedisUtil.java
  src/main/java/com/flexrate/flexrate_back/member/api/LoginController.java
  src/main/java/com/flexrate/flexrate_back/member/api/SignUpController.java
  src/main/java/com/flexrate/flexrate_back/member/application/DummyFinancialDataGenerator.java
  src/main/java/com/flexrate/flexrate_back/member/application/LoginService.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/application/SignupService.java
  src/main/java/com/flexrate/flexrate_back/member/application/VerificationCodeService.java
  src/main/java/com/flexrate/flexrate_back/member/application/WebAuthnService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/FidoCredentialRepository.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MfaLogRepository.java
  src/main/java/com/flexrate/flexrate_back/member/dto/AnalyzeConsumptionTypeResponse.java
  src/main/java/com/flexrate/flexrate_back/member/dto/LoginResponseDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/MfaLoginRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PasskeyAuthenticationDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PasskeyLoginRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PasskeyRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/PasswordLoginRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupPasswordRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupResponseDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/email-authentication.html
  src/test/java/com/flexrate/flexrate_back/loan/LoanTest.java
  src/test/java/com/flexrate/flexrate_back/member/application/MemberServiceTest.java
Labels: feat

#72 feat : 머신러닝 애플리케이션 도입
  docker-compose.yml
  fastapi/Dockerfile
  fastapi/main.py
  fastapi/model/normalized_rate_model_with_bounds.pkl
  fastapi/predictor.py
  fastapi/requirements.txt
  fastapi/schemas.py
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanProductService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/LoanReviewApplicationRequest.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
  src/main/java/com/flexrate/flexrate_back/member/application/SignupService.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupPasswordRequestDTO.java
Labels: feat

#66 chore: flyway 마이그레이션 파일 작성
  src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialDataType.java
  src/main/java/com/flexrate/flexrate_back/notification/enums/NotificationType.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitCategory.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V999__init_dev_dummy_data.sql
Labels: chore

#79 feat: 회원 신용 정보 산정 이력 테이블 및 신용점수 산정 이력 테이블 추가 & 변경에 따른 flyway 버전관리
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanReviewHistoryRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanReviewHistory.java
  src/main/java/com/flexrate/flexrate_back/member/domain/MemberCreditSummary.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitCategory.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__add_loan_review_history.sql
  src/main/resources/db/migration/V999__init_dev_dummy_data.sql
Labels: feat

#78 fix: selectProduct API 수정 및 관련 파일 추가
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanProductService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
Labels: fix

#82 feat: 사용자 대출 상태 조회 api 구현
  src/main/java/com/flexrate/flexrate_back/member/api/MemberController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
Labels: feat

#80 feat : 소비습관 리포트 생성 API 구현
  src/main/java/com/flexrate/flexrate_back/common/config/OpenAiConfig.java
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataRepository.java
  src/main/java/com/flexrate/flexrate_back/member/application/DummyFinancialDataGenerator.java
  src/main/java/com/flexrate/flexrate_back/member/application/SignupService.java
  src/main/java/com/flexrate/flexrate_back/member/dto/SignupPasswordRequestDTO.java
  src/main/java/com/flexrate/flexrate_back/member/enums/ConsumptionType.java
  src/main/java/com/flexrate/flexrate_back/report/api/ConsumptionHabitReportController.java
  src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportService.java
  src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportServiceImpl.java
  src/main/java/com/flexrate/flexrate_back/report/client/ConsumptionReportApiClient.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
  src/main/java/com/flexrate/flexrate_back/report/dto/ChatGPTRequest.java
  src/main/java/com/flexrate/flexrate_back/report/dto/ChatGPTResponse.java
  src/main/java/com/flexrate/flexrate_back/report/dto/Message.java
  src/main/java/com/flexrate/flexrate_back/report/scheduler/ConsumptionHabitReportScheduler.java
  src/main/resources/application.yml
Labels: feat

#85 Feat: 대출 금리 갱신 로직 구현
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialCategory.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/InterestRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/Interest.java
  src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java
Labels: feat

#87 fix : 신용점수 조회 혹은 평가 시 상위 퍼센티지 반환 추가
  src/main/java/com/flexrate/flexrate_back/financialdata/api/CreditScoreController.java
  src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
  src/main/java/com/flexrate/flexrate_back/financialdata/dto/CreditScoreResponse.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanApplicationRepository.java
Labels: fix

#90 Feat : 메인페이지 조회 기능 구현
  src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/InterestQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/InterestQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionRepository.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/Interest.java
  src/main/java/com/flexrate/flexrate_back/loan/dto/MainPageResponse.java
  src/main/java/com/flexrate/flexrate_back/member/api/MemberController.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
Labels: feat

#99 fix : 특정 회원의 지정 월에 대한 카테고리별 소비 통계 조회 json type으로 저장하고, 재호출 시 저장된 데이터 반환
  src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java
  src/main/java/com/flexrate/flexrate_back/report/application/ReportStatisticsService.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
Labels: fix

#107 chore: flyway 버전 관리 & 엔티티 필드 개선
  docker-compose.yml
  src/main/java/com/flexrate/flexrate_back/auth/api/TestTokenApiController.java
  src/main/java/com/flexrate/flexrate_back/common/TestController.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java
  src/main/java/com/flexrate/flexrate_back/loan/enums/ResidenceType.java
  src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
  src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
  src/main/resources/db/migration/V1000__init_dev_dummy_data_after_V4.sql
  src/main/resources/db/migration/V4__alter_loan_application.sql
  src/main/resources/db/migration/V5__alter_interest.sql
  src/main/resources/db/migration/V6__alter_user_financial_data.sql
  src/main/resources/db/migration/V7__alter_consumption_habit_report.sql
  src/main/resources/db/migration/V999__init_dev_dummy_data.sql.back
Labels: chore

#102 feat: 알림 페이지 API 구현
  src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/TokenAuthenticationFilter.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanApplicationRepository.java
  src/main/java/com/flexrate/flexrate_back/notification/api/NotificationController.java
  src/main/java/com/flexrate/flexrate_back/notification/application/NotificationEmitterService.java
  src/main/java/com/flexrate/flexrate_back/notification/application/NotificationService.java
  src/main/java/com/flexrate/flexrate_back/notification/domain/Notification.java
  src/main/java/com/flexrate/flexrate_back/notification/domain/repository/NotificationQueryRepository.java
  src/main/java/com/flexrate/flexrate_back/notification/domain/repository/NotificationQueryRepositoryImpl.java
  src/main/java/com/flexrate/flexrate_back/notification/domain/repository/NotificationRepository.java
  src/main/java/com/flexrate/flexrate_back/notification/dto/NotificationResponse.java
  src/main/java/com/flexrate/flexrate_back/notification/dto/NotificationSummaryDto.java
  src/main/java/com/flexrate/flexrate_back/notification/dto/UnreadCountResponse.java
  src/main/java/com/flexrate/flexrate_back/notification/enums/NotificationType.java
  src/main/java/com/flexrate/flexrate_back/notification/event/NotificationEvent.java
  src/main/java/com/flexrate/flexrate_back/notification/event/NotificationEventListener.java
  src/main/java/com/flexrate/flexrate_back/notification/event/NotificationEventPublisher.java
  src/main/java/com/flexrate/flexrate_back/notification/scheduler/MaturityNotificationScheduler.java
Labels: feat

#112 feat: MainPageResponse에 totalAmount와 repaymentMonth 추가
  src/main/java/com/flexrate/flexrate_back/loan/dto/MainPageResponse.java
  src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
Labels: feat

#116 fix: 만기일 당일 알림 추가
  src/main/java/com/flexrate/flexrate_back/notification/scheduler/MaturityNotificationScheduler.java
Labels: fix

#120 fix: 대출 심사 결과 갱신 메서드 추가 및 대출 신청 사전 정보 저장 로직 수정
  src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java
  src/main/java/com/flexrate/flexrate_back/loan/domain/LoanReviewHistory.java
Labels: fix

#122 feat : 소비 개선 리포트 가능 연월 조회 기능 구현
  src/main/java/com/flexrate/flexrate_back/financialdata/api/CreditScoreController.java
  src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
  src/main/java/com/flexrate/flexrate_back/report/api/ConsumptionHabitReportController.java
  src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportServiceImpl.java
Labels: feat

#124 fix : NotificationController 인증 principal로 교체
  src/main/java/com/flexrate/flexrate_back/notification/api/NotificationController.java
Labels: fix

#127 fix: 로그아웃 refreshToken 쿠키로 요청 받도록 수정
  src/main/java/com/flexrate/flexrate_back/member/api/LoginController.java
Labels: fix
